name: 'publish'
on:
  push:
    branches:
      - master

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.BURGER_GITHUB_TOKEN }}

      - name: node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: git config --global user.email "dangtpvt220695@gmail.com"
      - run: git config --global user.name "Dang Nguyen"
      - name: publish version
        run: npm version patch
      - name: publish
        run: npm publish --access publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
