name: 'publish'
on:
  push:
    branches:
      - master

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.BURGER_GITHUB_TOKEN }}

      - run: git config --global user.name 'Dang Nguyen'
      - run: git config --global user.email 'dangtpvt220695@gmail.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
      - name: node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: publish
        run: npm publish --access publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
